application: sql-buddy
version: 1
runtime: php
api_version: 1
# threadsafe: yes

handlers:
- url: /(.*\.(ico$|jpg$|png$|gif$))
  static_files: \1
  upload: (.*\.(ico$|jpg$|png$|gif$))
  application_readable: true

- url: /(.*\.(htm$|html$|css$|js$))
  static_files: \1
  upload: (.*\.(htm$|html$|css$|js$))
  application_readable: true

- url: /(.*\.(ico$|jpg$|png$|gif$))
  static_files: \1
  upload: (.*\.(ico$|jpg$|png$|gif$))
  application_readable: true

- url: /(.*\.(htm$|html$|css$|js$))
  static_files: \1
  upload: (.*\.(htm$|html$|css$|js$))
  application_readable: true

- url: /(.*\.(php$))
  script: \1
  login: admin

- url: /(.*\.(php$))
  script: \1
  login: admin

- url: /(.+)
  script: index.php
  login: admin

- url: /.*
  script: index.php
  login: admin
